steps:
  test:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - go mod download
      - go mod verify
      - go test -v ./...
      - go vet ./...
      - go fmt -s -l . | tee /tmp/fmt.out
      - |
        if [ -s /tmp/fmt.out ]; then
          echo "The following files are not formatted:"
          cat /tmp/fmt.out
          exit 1
        fi
    when:
      event: [push, pull_request]

  lint:
    image: golangci/golangci-lint:latest
    commands:
      - golangci-lint run
    when:
      event: [push, pull_request]

  build:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt main.go
      - ./rapt version
    when:
      event: [push, pull_request, tag]

  build-linux-amd64:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - export GOOS=linux GOARCH=amd64
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt-linux-amd64 main.go
      - ls -la rapt-linux-amd64
    when:
      event: tag

  build-linux-arm64:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - export GOOS=linux GOARCH=arm64
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt-linux-arm64 main.go
      - ls -la rapt-linux-arm64
    when:
      event: tag

  build-darwin-amd64:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - export GOOS=darwin GOARCH=amd64
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt-darwin-amd64 main.go
      - ls -la rapt-darwin-amd64
    when:
      event: tag

  build-darwin-arm64:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - export GOOS=darwin GOARCH=arm64
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt-darwin-arm64 main.go
      - ls -la rapt-darwin-arm64
    when:
      event: tag

  build-windows-amd64:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - export GOOS=windows GOARCH=amd64
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt-windows-amd64.exe main.go
      - ls -la rapt-windows-amd64.exe
    when:
      event: tag

  build-windows-arm64:
    image: golang:1.24-alpine
    commands:
      - apk add --no-cache git
      - export GOOS=windows GOARCH=arm64
      - go build -v -ldflags="-X 'codeberg.org/lig/rapt/cmd.Version=${CI_COMMIT_TAG:-dev}' -X 'codeberg.org/lig/rapt/cmd.Commit=${CI_COMMIT_SHA}' -X 'codeberg.org/lig/rapt/cmd.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)'" -o rapt-windows-arm64.exe main.go
      - ls -la rapt-windows-arm64.exe
    when:
      event: tag